# title: taghead.github.io
# email: taghead.github.io
# description: >- # this means to ignore newlines until "baseurl:"
#   A blog providing an informal insight towards
#   topics of interest. 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: taghead
# github_username:  taghead

# Build settings
# theme: minima
# plugins:
#   - jekyll-sass-converter
#   - jekyll-feed

site_version: 0.28

exclude:
   - /docs/
   - /README.md

include:
 - _pages

sass:
  style: compact